import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import FirstSection from "/components/home/FirstSection"
import SecondSection from "/components/home/SecondSection"

export default function Home() {

  const [isLogin , setLogin] = useState(false);

  return (
    <div className="m-0 p-0">
      <Head>
        <title>Curiosity Stream | Stay Curious</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>
       <div className='z-10'><Navbar  isLogin={isLogin} ></Navbar></div>
      <main className=''>
        
        <FirstSection></FirstSection>
        <SecondSection></SecondSection>
        <Footer></Footer>
      </main>
    </div>
  )
}


function Navbar({isLogin}){
  return(
    <div className=' fixed top-0 left-0 flex flex-row justify-between w-screen item-center bg-gradient-to-b from-gray-900 via-slate-900 to-transparent'>
      <div className='w-1/2'><Left></Left></div>
      <div className='w-1/2'><Right isLogin={isLogin}></Right></div>
    </div>
  );
}
function Left(){
  return(
    <div className='pl-2 pt-1'>
      <a href='/' className=''>
        <svg viewBox="0 0 102 35" fill="none" xmlns="http://www.w3.org/2000/svg" style={{height: "100%" ,width:"120px"}}>
          <title>Curiosity Stream</title>
          <path fillRule="evenodd" clipRule="evenodd" d="M97.672 19.293V6.229h4.184v13.064c0 2.508-1.626 5.042-4.184 5.865v3.519h-4.185V25.16a6.251 6.251 0 01-4.14-5.867V6.229h4.14v13.064c0 1.062.966 2.057 2.115 2.057 1.15 0 2.07-.995 2.07-2.058zM95.61 34.98c-1.221 0-2.211-1.025-2.211-2.291 0-1.267.99-2.291 2.21-2.291 1.222 0 2.211 1.024 2.211 2.29 0 1.267-.99 2.291-2.21 2.291z" fill="url(#logo_svg__paint0_linear)"></path>
          <path fillRule="evenodd" clipRule="evenodd" d="M6.245 25.039C2.8 25.039 0 22.252 0 18.826V6.35C0 2.925 2.801.09 6.245.09c3.442 0 6.242 2.835 6.242 6.26H8.31c0-1.143-.918-2.1-2.066-2.1-1.148 0-2.112.957-2.112 2.1v12.476c0 1.142.964 2.054 2.112 2.054a2.05 2.05 0 002.066-2.054h4.176c0 3.426-2.8 6.213-6.242 6.213zM20.615 25.121c-3.489 0-6.29-2.517-6.29-5.657V6.336h4.18v13.128c0 1.033.916 1.902 2.11 1.902 1.147 0 2.066-.869 2.066-1.902V6.336h4.177v13.128c0 3.14-2.8 5.657-6.243 5.657zM38.565 24.969h4.133V6.351h-4.133V24.97zM32.802 7.506V6.35h-4.13V24.97h4.13l-.02-12.166c-.007-2.562 4.22-2.756 4.22-2.756V6.323s-2.991.286-4.2 1.183zM50.961 10.072c-1.146 0-2.066.83-2.066 1.862v7.521c0 1.035.92 1.906 2.066 1.906 1.149 0 2.064-.871 2.064-1.906v-7.52c0-1.033-.915-1.863-2.064-1.863zm0 15.049c-3.442 0-6.242-2.52-6.242-5.666v-7.52c0-3.101 2.8-5.623 6.242-5.623 3.444 0 6.245 2.522 6.245 5.622v7.521c0 3.146-2.801 5.666-6.245 5.666zM65.33 13.877c3.444 0 6.244 2.522 6.244 5.623 0 3.14-2.8 5.664-6.244 5.664-3.49 0-6.289-2.524-6.289-5.664h4.179c0 1.076.918 1.9 2.11 1.9 1.15 0 2.065-.824 2.065-1.9 0-1.033-.916-1.86-2.11-1.86-3.444 0-6.244-2.524-6.244-5.623 0-3.142 2.8-5.664 6.289-5.664 3.444 0 6.244 2.522 6.244 5.664h-4.179c0-1.075-.916-1.9-2.065-1.9-1.192 0-2.11.825-2.11 1.9 0 1.033.918 1.86 2.11 1.86zM73.181 24.969h4.134V6.333h-4.134V24.97zM85.532 20.8H87.6v4.167h-2.067c-3.444 0-6.242-2.795-6.242-6.232V0h4.132v6.333l4.177.006v4.059h-4.177v8.337c0 1.147.965 2.064 2.11 2.064zM.319 33.517h.737c.052.404.219.741.916.741.455 0 .777-.247.777-.618 0-.37-.19-.511-.858-.618C.906 32.893.44 32.601.44 31.848c0-.658.576-1.152 1.434-1.152.887 0 1.416.393 1.497 1.163h-.702c-.075-.421-.323-.601-.795-.601-.467 0-.709.219-.709.528 0 .326.139.489.853.59.967.13 1.468.399 1.468 1.203 0 .696-.605 1.241-1.514 1.241-1.123 0-1.596-.545-1.653-1.303zM8.59 31.337H7.442v-.59h3.064v.59H9.361v3.427H8.59v-3.428zM16.157 32.606c.513 0 .784-.213.784-.64v-.023c0-.46-.294-.618-.784-.618h-.616v1.281h.616zm-1.382-1.86h1.382c.904 0 1.538.36 1.538 1.18v.023c0 .63-.403.95-.916 1.079l1.158 1.736h-.83l-1.076-1.624h-.49v1.624h-.766v-4.017zM22.199 30.747h2.574v.59h-1.808v1.1h1.451V33h-1.451v1.174h1.906v.59h-2.672v-4.017zM30.118 33.224h1.215l-.604-1.865-.61 1.865zm.156-2.477h1.002l1.359 4.017h-.795l-.328-.994H29.94l-.323.994h-.72l1.377-4.017zM36.915 30.747h1.025l1.082 2.742 1.06-2.742h1.014v4.017h-.766V31.73l-1.227 3.034h-.248l-1.25-3.034v3.034h-.69v-4.017z" fill="#F7F7F7"></path>
          <defs><linearGradient id="logo_svg__paint0_linear" x1="85.307" y1="15.516" x2="104.187" y2="28.231" gradientUnits="userSpaceOnUse"><stop stopColor="#ECC334"></stop><stop offset="1" stopColor="#EB8B4C"></stop></linearGradient></defs>
          </svg>
        {/* <img className='w-28 h-11 object-center object-cover' src="/Logo/mainLogo.svg"></img> */}
      </a>
    </div>
  );
}

function Right(){
  return(
    <div className='w-full tracking-wider  pt-2 pr-2 text-sm flex flex-row space-x-1 justify-end items-center'>
      <div className='w-1/3 text-gray-100 py-2   text-center font-sans font-medium brightness-110'><h5 className='block w-full'>Sign In</h5></div>
      <Link href="/signUp"><a><div className=' max-w-xs scale-75 bg-gradient-to-br rounded from-yellow-500 py-3 px-1 to-yellow-600 text-center font-sans font-medium brightness-110'><h5>Sign Up</h5></div></a></Link>
    </div>
  );
}
function Footer(){
  return(
    <div className='flex flex-col item-center justify-start bg-black text-white border-t-2 border-gray-600  pt-4 px-2'>
      <div className='flex flex-row item-center justify-between px-2'>
          <div><img className='w-12 h-12' src="/icon.svg"></img></div>
          <div><AllIcons></AllIcons></div>
      </div>
      <div className='grid grid-cols-2 my-4  font-sans text-sm px-3 gap-y-1 font-normal text-gray-400'>
        <div className='hover:text-white'>Gift Cards</div>
        <div className='hover:text-white'>Help Center</div>
        <div className='hover:text-white'>About</div>
        <div className='hover:text-white'>Careers</div>
        <div className='hover:text-white'>Accessibility</div>
        <div className='hover:text-white'>Investors</div>
        <div className='hover:text-white'>Press</div>
        <div className='hover:text-white'>Corporate Subscriptions</div>
      </div>
      <div className='border-t-2 my-4 text-sm border-gray-600 flex flex-row justify-between py-2 item-center text-gray-400'>
        <div className="flex flex-row justify-start item-center space-x-2">
          <div className='hover:text-white'><h5>Privacy</h5></div>
          <div className='hover:text-white'><h5>Terms</h5></div>
        </div>
        
        <div>
          <h5>© 2022 Curiosity Stream Inc.</h5>
        </div>
      </div>
    </div>
  );
}
function AllIcons(){
  return(
    <div className='flex flex-row space-x-1 justify-end items-center'>
      <div><svg className='w-7 h-7 fill-gray-400 hover:fill-gray-300' xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2.917 16.083c-2.258 0-4.083-1.825-4.083-4.083s1.825-4.083 4.083-4.083c1.103 0 2.024.402 2.735 1.067l-1.107 1.068c-.304-.292-.834-.63-1.628-.63-1.394 0-2.531 1.155-2.531 2.579 0 1.424 1.138 2.579 2.531 2.579 1.616 0 2.224-1.162 2.316-1.762h-2.316v-1.4h3.855c.036.204.064.408.064.677.001 2.332-1.563 3.988-3.919 3.988zm9.917-3.5h-1.75v1.75h-1.167v-1.75h-1.75v-1.166h1.75v-1.75h1.167v1.75h1.75v1.166z"/></svg></div>
      <div><svg className='w-7 h-7 fill-gray-300 hover:fill-gray-200' xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M14.829 6.302c-.738-.034-.96-.04-2.829-.04s-2.09.007-2.828.04c-1.899.087-2.783.986-2.87 2.87-.033.738-.041.959-.041 2.828s.008 2.09.041 2.829c.087 1.879.967 2.783 2.87 2.87.737.033.959.041 2.828.041 1.87 0 2.091-.007 2.829-.041 1.899-.086 2.782-.988 2.87-2.87.033-.738.04-.96.04-2.829s-.007-2.09-.04-2.828c-.088-1.883-.973-2.783-2.87-2.87zm-2.829 9.293c-1.985 0-3.595-1.609-3.595-3.595 0-1.985 1.61-3.594 3.595-3.594s3.595 1.609 3.595 3.594c0 1.985-1.61 3.595-3.595 3.595zm3.737-6.491c-.464 0-.84-.376-.84-.84 0-.464.376-.84.84-.84.464 0 .84.376.84.84 0 .463-.376.84-.84.84zm-1.404 2.896c0 1.289-1.045 2.333-2.333 2.333s-2.333-1.044-2.333-2.333c0-1.289 1.045-2.333 2.333-2.333s2.333 1.044 2.333 2.333zm-2.333-12c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.958 14.886c-.115 2.545-1.532 3.955-4.071 4.072-.747.034-.986.042-2.887.042s-2.139-.008-2.886-.042c-2.544-.117-3.955-1.529-4.072-4.072-.034-.746-.042-.985-.042-2.886 0-1.901.008-2.139.042-2.886.117-2.544 1.529-3.955 4.072-4.071.747-.035.985-.043 2.886-.043s2.14.008 2.887.043c2.545.117 3.957 1.532 4.071 4.071.034.747.042.985.042 2.886 0 1.901-.008 2.14-.042 2.886z"/></svg></div>
      <div><svg className='w-7 h-7 fill-gray-400 hover:fill-gray-300' xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.066 9.645c.183 4.04-2.83 8.544-8.164 8.544-1.622 0-3.131-.476-4.402-1.291 1.524.18 3.045-.244 4.252-1.189-1.256-.023-2.317-.854-2.684-1.995.451.086.895.061 1.298-.049-1.381-.278-2.335-1.522-2.304-2.853.388.215.83.344 1.301.359-1.279-.855-1.641-2.544-.889-3.835 1.416 1.738 3.533 2.881 5.92 3.001-.419-1.796.944-3.527 2.799-3.527.825 0 1.572.349 2.096.907.654-.128 1.27-.368 1.824-.697-.215.671-.67 1.233-1.263 1.589.581-.07 1.135-.224 1.649-.453-.384.578-.87 1.084-1.433 1.489z"/></svg></div>
      <div><svg className='w-7 h-7 fill-gray-300 hover:fill-gray-200' xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z"/></svg></div>
    </div>
  );
}